import torch

# CONFIGURACIÓN DEL ENTORNO
ENV_NAME = 'CartPole-v1'
NUM_EPISODES = 500
MAX_STEPS = 500

# HIPERPARÁMETROS COMUNES
LEARNING_RATE = 0.001
GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_END = 0.01
EPSILON_DECAY = 0.995
BATCH_SIZE = 64
MEMORY_SIZE = 10000
TARGET_UPDATE_FREQ = 10

# ARQUITECTURA DE RED NEURONAL
HIDDEN_LAYERS = [128, 128]

# PARÁMETROS DE ENTRENAMIENTO
SAVE_EVERY = 50
PRINT_EVERY = 10

# EARLY STOPPING
EARLY_STOP_THRESHOLD = 475
EARLY_STOP_PATIENCE = 20

# DISPOSITIVO (CPU por defecto)
DEVICE = torch.device("cpu")

# RUTAS DE GUARDADO
SAVE_MODEL_PATH = 'models/'
SAVE_PLOTS_PATH = 'plots/'
SAVE_METRICS_PATH = 'metrics/'

# SEMILLA PARA REPRODUCIBILIDAD
RANDOM_SEED = 42
