import torch

# CONFIGURACIÓN DEL ENTORNO
ENV_NAME = 'CartPole-v1'
NUM_EPISODES = 2000 
MAX_STEPS = 500

# HIPERPARÁMETROS COMUNES 
LEARNING_RATE = 0.001 
GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_END = 0.01
EPSILON_DECAY = 0.995
BATCH_SIZE = 64
MEMORY_SIZE = 10000  
TARGET_UPDATE_FREQ = 10 

# ARQUITECTURA DE RED NEURONAL
HIDDEN_LAYERS = [64, 64]  

# PARÁMETROS DE ENTRENAMIENTO
SAVE_EVERY = 100
PRINT_EVERY = 50

# EARLY STOPPING
EARLY_STOP_THRESHOLD = 450 
EARLY_STOP_PATIENCE = 10 

if not torch.cuda.is_available():
    raise RuntimeError("CUDA no disponible")

DEVICE = torch.device("cuda")
print(f"Usando GPU: {torch.cuda.get_device_name(0)}")

# RUTAS DE GUARDADO
SAVE_MODEL_PATH = 'models/'
SAVE_PLOTS_PATH = 'plots/'
SAVE_METRICS_PATH = 'metrics/'

# SEMILLA PARA REPRODUCIBILIDAD
RANDOM_SEED = 42
