import torch

# CONFIGURACIÓN DEL ENTORNO
ENV_NAME = 'CartPole-v1'
NUM_EPISODES = 2000  # Incrementado para aprovechar GPU
MAX_STEPS = 500

# HIPERPARÁMETROS COMUNES
LEARNING_RATE = 0.0005  
GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_END = 0.01
EPSILON_DECAY = 0.9995  
BATCH_SIZE = 128
MEMORY_SIZE = 50000
TARGET_UPDATE_FREQ = 50

# ARQUITECTURA DE RED NEURONAL (Red más profunda)
HIDDEN_LAYERS = [256, 256, 128]

# PARÁMETROS DE ENTRENAMIENTO
SAVE_EVERY = 100
PRINT_EVERY = 50

# EARLY STOPPING
EARLY_STOP_THRESHOLD = 475
EARLY_STOP_PATIENCE = 50

if not torch.cuda.is_available():
    raise RuntimeError("CUDA no disponible")

DEVICE = torch.device("cuda")
print(f"Usando GPU: {torch.cuda.get_device_name(0)}")

# RUTAS DE GUARDADO
SAVE_MODEL_PATH = 'models/'
SAVE_PLOTS_PATH = 'plots/'
SAVE_METRICS_PATH = 'metrics/'

# SEMILLA PARA REPRODUCIBILIDAD
RANDOM_SEED = 42
